### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by HyTom** [reykjaviks/britionary#1]
Koodi tosi helposti ymmärrettävää!
Hyvin kommentoitua.
Käytin pitkän aikaa siihen että yritin löytää jotain mitä arvostella mutta koodi oli näköjään jätetty ärsyttävän hyvään kuntoon.
Ladattuani testailin sanoja ja kaikki tuntui toimivan oikein, mutta en saanut ohjelmaa antamaan minulle sanan cookie britti synonyymiä biscuit. 

Hyvältä näyttää, onnea vikalle viikolle!

**Comment by mantelimaito** [comment]
Hei ja kiitos palautteesta! Mukava kuulla, että rakennetta on ollut helppo lukea. Yritän korjata bugit ja ehkä laajentaa toiminnallisuutta vielä tällä viikolla. Onnea myös oman ohjelman tekoon.
